language: cpp

compiler: gcc

before_install:
  # Set package repoository.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  
  # Update the system.
  - sudo apt-get -qq update
  
  # Get GCC 4.8 (for C++11 support)
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  
install:
  
  # Get GMP (GNU Multiprecision Arithmetic Library)
  # Get LibConfig (for Obelisk until swtich to boost::program_options)
  - sudo apt-get -qq install libgmp-dev libconfig++-dev
  
script: 
  - ./boost.sh
  - ./build.sh CFLAGS="-Os -s"
