language: cpp

compiler: gcc

branches:
  # Build only from master, when master changes.
  only: master
    
before_install:
  # Set package repoository.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  
  # Update the system.
  - sudo apt-get -qq update
  
  # Get GCC 4.8 (for C++11 support)
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  
install:
  
  # Get GMP (GNU Multiprecision Arithmetic Library)
  # Get LibConfig (for Obelisk until swtich to boost::program_options)
  - sudo apt-get -qq install libgmp-dev libconfig++-dev

  # Install required boost components at the minimum version required.
  - ./boost.sh

script:
  # Build the master branch and all locally-built dependencies.
  - ./build.sh CFLAGS="-s"
